# Generated by Django 3.2.7 on 2021-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20211001_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
